runtime: go
api_version: go1.9
application: x-po-201808
module: default

env_variables:
  APP_ENV: 'production'

includes:
  - lib/common.yaml
  - lib/secret.yaml

skip_files:
  - ^(.*/)?test.go$
  - ^(.*/)?testkit.go
  - ^(.*/)?testarator.go
  - ^(.*)/appengine/aetest/(.*)
  - ^(.*)/pkg/(.*)

handlers:
  - url: /admin/.*
    login: admin
    script: _go_app
